[nushell]
depends = []

[nushell.files]
"nushell/config.nu" = "~/.config/nushell/config.nu"
"nushell/env.nu" = "~/.config/nushell/env.nu"
"nushell/autoload/01-aliases.nu" = "~/.config/nushell/autoload/01-aliases.nu"

[git.files]
"git/config" = "~/.config/git/config"
"git/attributes" = "~/.config/git/attributes"
"git/ignore" = "~/.config/git/ignore"

[editorconfig.files]
"editorconfig" = "~/.editorconfig"

[bat.files]
"bat/config" = "~/.config/bat/config"

[ripgrep.files]
"ripgrep/config" = "~/.config/ripgrep/config"

[fzf.files]
"fzf/config" = "~/.config/fzf/config"

[mise.files]
"mise/config.toml" = "~/.config/mise/config.toml"
